### ISSUE TITLE
Check should occur after fixture teardown

### ISSUE THREAD

**Issue by stscieisenhamer** [astropy/pytest-openfiles#32]
If an open file is provided by a fixture, the plugin reports an open file error regardless of the fact that the fixture properly closes the file.

Example code that is run by `pytest --open-files test.py`, where `test.py` is as follows. The expectation is that this should pass without error.

```
import pytest

@pytest.fixture
def provide_fh(tmp_path):
    """Provide a file handle"""

    # Create a file just to have one.
    path = tmp_path / 'junk.txt'
    fd = open(path, 'w')
    fd.write('There is junk in them hills\n')
    fd.close()

    with open(path) as read_fd:
        yield read_fd


def test_teardown(provide_fh):
    assert True
```

**Comment by stscieisenhamer** [comment]
and it seems a pr is in the works for this...

**Comment by mhvk** [comment]
Just ran into this as well, although in my case it is not a fixture, but a pair of `setup` and `teardown` methods for a class. If there is a PR, would be happy to check that it solves my case as well.

Slightly more generally, one can imagine having a class of tests which has `setup_class`/`teardown_class` methods, i.e., it would be nice if one could control at what level the open file check is done....

**Comment by jdavies-st** [comment]
To further the discussion along here, if a test fixture opens a file and passes along that open file handle to a test, then yes, it will cause the plugin to issue an error.  But perhaps this is not good fixture design?  A pytest fixture can supply something to tests that may not be run together on the same core, or even on the same machine, may be accessed by separate tests in parallel using `pytest-xdist`, may have function- or module-scoped persistence, etc.

It would be nice to get a sense of what this plugin is expecting fixtures to be doing.  Are fixtures managing resources or are tests?  Does it make sense for fixtures to be trying to manage resources, given that they can be used by multiple tests, depending on their scope?

**Comment by pllim** [comment]
At some point, there was a conversation somewhere that talked about maybe we should retire `pytest-openfiles` altogether and rely on `pytest` built-in warning system to catch `ResourceWarning`.

**Comment by jdavies-st** [comment]
So you think something like `pytest -Wd` covers all the bases, as long as the warnings are then converted to errors?  As linked through in #40?

**Comment by pllim** [comment]
Maybe @saimn can chime in; somehow his name popped up in my memory. 😆

**Comment by mhvk** [comment]
Would indeed be nice if we can just use the native mechanism!

**Comment by saimn** [comment]
Yeah, last time I looked, I saw some weird behavior with this plugin that I cannot explain (or don't want to spend my time on this ;)) #39, and on the other side I think that Python itself is more reliable to detect leaked file descriptors. So yes, turning `ResourceWarning` into errors seems the best way to go.

**Comment by jdavies-st** [comment]
So to further discussion,

```python
# test_foo.py

def test_foo():
    fd = open(__file__)
    fd = None
```

And if I run it:

```
$ pytest test_foo.py 
================================= test session starts ==================================
platform darwin -- Python 3.9.1, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /Users/jdavies/dev/jwst, configfile: setup.cfg
plugins: requests-mock-1.8.0, cov-2.11.1, ci-watson-0.5, asdf-2.7.2, openfiles-0.5.0, doctestplus-0.9.0
collected 1 item                                                                       

test_foo.py .                                                                    [100%]

================================== 1 passed in 0.03s ===================================
```

Passes just fine.

```
$ pytest test_foo.py --open-files
================================= test session starts ==================================
platform darwin -- Python 3.9.1, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /Users/jdavies/dev/jwst, configfile: setup.cfg
plugins: requests-mock-1.8.0, cov-2.11.1, ci-watson-0.5, asdf-2.7.2, openfiles-0.5.0, doctestplus-0.9.0
collected 1 item                                                                       

test_foo.py .                                                                    [100%]

================================== 1 passed in 0.03s ===================================
```

Surprisingly, it passes just fine.  Unexpected!

```
$ pytest test_foo.py -Wd
================================= test session starts ==================================
platform darwin -- Python 3.9.1, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /Users/jdavies/dev/jwst, configfile: setup.cfg
plugins: requests-mock-1.8.0, cov-2.11.1, ci-watson-0.5, asdf-2.7.2, openfiles-0.5.0, doctestplus-0.9.0
collected 1 item                                                                       

test_foo.py .                                                                    [100%]

=================================== warnings summary ===================================
jwst/test_foo.py::test_foo
  /Users/jdavies/dev/jwst/jwst/test_foo.py:3: ResourceWarning: unclosed file <_io.TextIOWrapper name='/Users/jdavies/dev/jwst/jwst/test_foo.py' mode='r' encoding='UTF-8'>
    fd = None

-- Docs: https://docs.pytest.org/en/stable/warnings.html
============================= 1 passed, 1 warning in 0.03s =============================
```

Only `pytest -Wd` reports the warning.

If I try to convert to errors, it doesn't work:

```
$ pytest test_foo.py -W error::ResourceWarning
================================= test session starts ==================================
platform darwin -- Python 3.9.1, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /Users/jdavies/dev/jwst, configfile: setup.cfg
plugins: requests-mock-1.8.0, cov-2.11.1, ci-watson-0.5, asdf-2.7.2, openfiles-0.5.0, doctestplus-0.9.0
collected 1 item                                                                       

test_foo.py .                                                                    [100%]

=================================== warnings summary ===================================
jwst/test_foo.py::test_foo
  /Users/jdavies/miniconda3/envs/jwst/lib/python3.9/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <_io.FileIO [closed]>
  
  Traceback (most recent call last):
    File "/Users/jdavies/dev/jwst/jwst/test_foo.py", line 3, in test_foo
      fd = None
  ResourceWarning: unclosed file <_io.TextIOWrapper name='/Users/jdavies/dev/jwst/jwst/test_foo.py' mode='r' encoding='UTF-8'>
  
    warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))

-- Docs: https://docs.pytest.org/en/stable/warnings.html
============================= 1 passed, 1 warning in 0.03s =============================
```

And if I use a big net:

```
$ pytest test_foo.py -W error
================================= test session starts ==================================
platform darwin -- Python 3.9.1, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /Users/jdavies/dev/jwst, configfile: setup.cfg
plugins: requests-mock-1.8.0, cov-2.11.1, ci-watson-0.5, asdf-2.7.2, openfiles-0.5.0, doctestplus-0.9.0
collected 1 item                                                                       

test_foo.py F                                                                    [100%]

======================================= FAILURES =======================================
_______________________________________ test_foo _______________________________________

cls = <class '_pytest.runner.CallInfo'>
func = <function call_runtest_hook.<locals>.<lambda> at 0x7fb5507e8820>, when = 'call'
reraise = (<class '_pytest.outcomes.Exit'>, <class 'KeyboardInterrupt'>)

    @classmethod
    def from_call(
        cls,
        func: "Callable[[], TResult]",
        when: "Literal['collect', 'setup', 'call', 'teardown']",
        reraise: Optional[
            Union[Type[BaseException], Tuple[Type[BaseException], ...]]
        ] = None,
    ) -> "CallInfo[TResult]":
        excinfo = None
        start = timing.time()
        precise_start = timing.perf_counter()
        try:
>           result: Optional[TResult] = func()

../../../miniconda3/envs/jwst/lib/python3.9/site-packages/_pytest/runner.py:311: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../../miniconda3/envs/jwst/lib/python3.9/site-packages/_pytest/runner.py:255: in <lambda>
    lambda: ihook(item=item, **kwds), when=when, reraise=reraise
../../../miniconda3/envs/jwst/lib/python3.9/site-packages/pluggy/hooks.py:286: in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
../../../miniconda3/envs/jwst/lib/python3.9/site-packages/pluggy/manager.py:93: in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
../../../miniconda3/envs/jwst/lib/python3.9/site-packages/pluggy/manager.py:84: in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
../../../miniconda3/envs/jwst/lib/python3.9/site-packages/_pytest/unraisableexception.py:88: in pytest_runtest_call
    yield from unraisable_exception_runtest_hook()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

    def unraisable_exception_runtest_hook() -> Generator[None, None, None]:
        with catch_unraisable_exception() as cm:
            yield
            if cm.unraisable:
                if cm.unraisable.err_msg is not None:
                    err_msg = cm.unraisable.err_msg
                else:
                    err_msg = "Exception ignored in"
                msg = f"{err_msg}: {cm.unraisable.object!r}\n\n"
                msg += "".join(
                    traceback.format_exception(
                        cm.unraisable.exc_type,
                        cm.unraisable.exc_value,
                        cm.unraisable.exc_traceback,
                    )
                )
>               warnings.warn(pytest.PytestUnraisableExceptionWarning(msg))
E               pytest.PytestUnraisableExceptionWarning: Exception ignored in: <_io.FileIO [closed]>
E               
E               Traceback (most recent call last):
E                 File "/Users/jdavies/dev/jwst/jwst/test_foo.py", line 3, in test_foo
E                   fd = None
E               ResourceWarning: unclosed file <_io.TextIOWrapper name='/Users/jdavies/dev/jwst/jwst/test_foo.py' mode='r' encoding='UTF-8'>

../../../miniconda3/envs/jwst/lib/python3.9/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning
=============================== short test summary info ================================
FAILED test_foo.py::test_foo - pytest.PytestUnraisableExceptionWarning: Exception ign...
================================== 1 failed in 0.17s ===================================
```
Pytest does some very nutty capturing and re-emitting of exceptions.  Hmm.

**Comment by pllim** [comment]
This plugin should no longer be used, please see:

* https://github.com/astropy/pytest-openfiles/pull/44
